#include <gtk/gtk.h>
#include <webkit2/webkit2.h>
#include <locale.h>
#include <string.h>

// This will be generated by xxd -i index.html > html_embedded.h
#include "html_embedded.h"

static void destroy_window_cb(GtkWidget* widget, gpointer data) {
    gtk_main_quit();
}

int main(int argc, char* argv[]) {
    setlocale(LC_ALL, "");
    gtk_init(&argc, &argv);

    // Create window
    GtkWidget* window = gtk_window_new(GTK_WINDOW_TOPLEVEL);
    gtk_window_set_default_size(GTK_WINDOW(window), 1000, 800);
    g_signal_connect(window, "destroy", G_CALLBACK(destroy_window_cb), NULL);

    // Create web view
    WebKitWebView* web_view = WEBKIT_WEB_VIEW(webkit_web_view_new());

    // Build a data URI from the embedded HTML
    // Note: xxd gives us `unsigned char index_html[]` and `unsigned int index_html_len`
    // We need to URL-encode the HTML to use in a data URI. For simplicity, we'll use
    // g_uri_escape_string (requires GLib). Alternatively, we can use a custom scheme.
    // A simple approach: use a custom "app" scheme and handle it.
    // Here we'll use a data URI with simple escaping; for full correctness, a custom scheme is better.
    // For this example, we assume the HTML is small and doesn't contain problematic chars.
    // A robust way: use webkit_web_view_load_bytes() with a "text/html" MIME type.
    // Let's use that.

    GBytes* bytes = g_bytes_new(index_html, index_html_len);
    webkit_web_view_load_bytes(web_view, bytes, "text/html", NULL, NULL);
    g_bytes_unref(bytes);

    gtk_container_add(GTK_CONTAINER(window), GTK_WIDGET(web_view));
    gtk_widget_show_all(window);
    gtk_main();

    return 0;
}